### ISSUE TITLE
Improve print-view

### ISSUE THREAD

**Issue by Klap-in** [Klap-in/dokuwiki-plugin-bookcreator#33]
===== print.css =====
To prevent the printing of the toolbar..

``` css
.dokuwiki div.bookcreator__panel { display: none }
.dokuwiki div.bookcreator__ { display: none }
```

From: https://www.dokuwiki.org/plugin:bookcreator:discussion
